
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.output_cup;

/** CUP generated interface containing symbol constants. */
public interface Token {
  /* terminals */
  public static final int FUNCTION = 23;
  public static final int GE = 45;
  public static final int UMINUS = 40;
  public static final int ENDVAR = 22;
  public static final int INTEGER = 3;
  public static final int INTEGER_CONST = 7;
  public static final int SEMI = 19;
  public static final int OUT = 27;
  public static final int MINUS = 39;
  public static final int REF = 13;
  public static final int WRITE = 51;
  public static final int TYPERETURN = 25;
  public static final int NOT = 43;
  public static final int AND = 41;
  public static final int LT = 46;
  public static final int RPAR = 16;
  public static final int ENDFUNCTION = 24;
  public static final int ENDPROCEDURE = 12;
  public static final int OR = 42;
  public static final int COMMA = 18;
  public static final int WRITERETURN = 52;
  public static final int DIV = 37;
  public static final int PLUS = 36;
  public static final int ASSIGN = 20;
  public static final int IF = 28;
  public static final int ENDWHILE = 35;
  public static final int ID = 26;
  public static final int LE = 47;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 14;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int EQ = 48;
  public static final int DOLLARSIGN = 50;
  public static final int REAL = 2;
  public static final int TIMES = 38;
  public static final int COLON = 17;
  public static final int ENDIF = 32;
  public static final int ELSE = 29;
  public static final int READ = 53;
  public static final int WHILE = 33;
  public static final int REAL_CONST = 6;
  public static final int THEN = 31;
  public static final int NE = 49;
  public static final int LPAR = 15;
  public static final int STRING = 4;
  public static final int FALSE = 10;
  public static final int STRING_CONST = 8;
  public static final int GT = 44;
  public static final int VAR = 21;
  public static final int ELIF = 30;
  public static final int PROCEDURE = 11;
  public static final int DO = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "REAL",
  "INTEGER",
  "STRING",
  "BOOLEAN",
  "REAL_CONST",
  "INTEGER_CONST",
  "STRING_CONST",
  "TRUE",
  "FALSE",
  "PROCEDURE",
  "ENDPROCEDURE",
  "REF",
  "RETURN",
  "LPAR",
  "RPAR",
  "COLON",
  "COMMA",
  "SEMI",
  "ASSIGN",
  "VAR",
  "ENDVAR",
  "FUNCTION",
  "ENDFUNCTION",
  "TYPERETURN",
  "ID",
  "OUT",
  "IF",
  "ELSE",
  "ELIF",
  "THEN",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDWHILE",
  "PLUS",
  "DIV",
  "TIMES",
  "MINUS",
  "UMINUS",
  "AND",
  "OR",
  "NOT",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "DOLLARSIGN",
  "WRITE",
  "WRITERETURN",
  "READ"
  };
}

